### PR TITLE
Add/fix links inside endpoint descriptions

### PR DESCRIPTION
**Pull request by bertramakers**
### Added

- Added links inside endpoint descriptions where another endpoint was mentioned

### Fixed

- Fixed some broken links in endpoint descriptions

### CODE REVIEW

**Review by LucWollants — CHANGES_REQUESTED** [review]
I noticed a few more broken links:
- Events
  - Inside `Get event details` the link inside `@id` to the event.json
  - Inside `Update calendar` the link inside the `calendarType` to the event.json
  - Inside `Update major info` various links inside `calendar`
  - Inside `Copy an event` various links inside the body
- Organizers
  - Inside `Create organizer` the `event` link inside the body
  - Inside `Get organizer details` the `organizer` link inside the body
- Places
  - Inside the `Get place details` the `place` link inside the body
  - Inside the `Update available from` the `place` link inside the body

**Comment by bertramakers** [comment]
Good finds, but this PR currently focuses on the descriptions. OK if you or I open another PR for those you found when either of us has some time?

**Review by LucWollants — APPROVED** [review]
Follow-up PR will be created to fix some other broken links.

**Comment by bertramakers** [comment]
I've created a ticket for that: https://jira.uitdatabank.be/browse/III-4532

**Pull request merged**
